source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "~> 8.0.2"
gem "puma"
gem "sqlite3"
gem "propshaft"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook", "~> 2.0"

gem "polaris_rails", path: "../"

group :development do
  gem "listen"
  gem "web-console"
end
